#!/bin/bash
echo "========================================="
echo "快速修复步骤"
echo "========================================="
echo ""
echo "1. 删除有问题的架构标签:"
echo "   ./delete_tags.sh delete-arch-tags y"
echo ""
echo "2. 提交工作流修复:"
echo "   git add .github/workflows/build-and-push.yml"
echo "   git commit -m 'fix: 修复构建配置，确保架构标签是单个镜像'"
echo "   git push origin main"
echo ""
echo "3. 在 GitHub Actions 中手动触发工作流重新构建"
echo ""
echo "4. 构建完成后验证:"
echo "   docker manifest inspect ghcr.io/acmen0102/linknlink-remote-frpc:amd64"
echo "   应该看到单个镜像，不是 manifest list"
